### PR TITLE
Changed to run in python3+

### PR DESCRIPTION
**Pull request by guruvyasa**
Changed the print statement to make this code work under python3

### CODE REVIEW

**Comment by shantnu** [comment]
Can you just change the existing CV3 file instead of creating a new one? Thanks

**Comment by guruvyasa** [comment]
Yeah sure. But if i do that, then it will not run in python2. Shall i put the old one as a comment?

**Comment by shantnu** [comment]
Python 2 supports print("hello") format.

Modify face_detect_cv3.py as well

**Comment by guruvyasa** [comment]
Oh. Thanks for that. I had never used that version of print in python2. I have made the changes. Please check it out.

**Comment by shantnu** [comment]
have you updated the pull request? Cause I still see the old file.

**Pull request closed without merging**
