### PR TITLE
Add live webcam example

### PR DESCRIPTION
**Pull request by void4**
Not sure if this is sensible.

### CODE REVIEW

**Comment by shantnu** [comment]
Is this OpenCV2 or 3?

**Comment by void4** [comment]
I have tested it with v3.2.0

**Comment by shantnu** [comment]
Okay.

Before I merge this is, can you please put this comment on the top:

# Tested with OpenCV3

Because someone _will_ try to use CV2 and then raise a bug.....

**Comment by void4** [comment]
Done.

**Comment by amritsinghbains** [comment]
How to use a video on place of a web cam?

**Pull request merged**
